### ISSUE TITLE
'emergency department admit to inpatient hospital stay' and 'sexual orientation identity datum' share the same IRI

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#10]

**Comment by CDowland** [comment]
This is one of the identity datum terms that we deprecated. The annotations include both the labels you mentioned, as well as some annotations that were intended to go with 'sexual orientation identity datum' and some that were intended to go with 'emergency department admit to inpatient hospital state.' 

I propose we remove the annotations intended to go with 'emergency department admit to inpatient hospital stay' from the now deprecated term, and use them in creating a new term with its own IRI for 'emergency department admit to inpatient hospital stay.'

**Comment by CDowland** [comment]
Since this is a class we'll need for the ENCOUNTER table, I went ahead and worked on this task. Here are the steps I took:

- First, I duplicated the class so there'd be a new version with a new IRI.
- On the one that already existed, I removed all the annotations that were associated with 'emergency department admit to inpatient hospital stay', leaving it as just the obsoleted 'sexual orientation identity datum.'
- Then, on the new one, I removed all the annotations associated with 'sexual orientation identity datum,' leaving just the ones for 'emergency department admit to inpatient hospital stay,' and removed "obsoleted" from the beginning of its label (in removing the annotations from the other term, I also removed the one marking it as deprecated).
- Then, I placed it under the correct parent class ('health care encounter'), changed "healthcare" to "health care" in the definition, and corrected the annotation on the definition (it had been annotated as 'term editor'). 
- Finally, I saved the above changes and pushed them to the development branch.
