### ISSUE TITLE
NTR: 'PCORnet medical procedure'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#20]
label: PCORnet medical procedure
definition: A planned process that realizes a patient role.
logical definition: subclassOf realizes 'patient role'
Term editor: William R. Hogan
Contributors: Matthew Diller, S. Clint Dowland, Sarah Bost

**Comment by CDowland** [comment]
Two concerns:

1. Doesn't every health care encounter realize a patient role? If so, then this definition implies that every instance of health care encounter (since it is a planned process and realizes a patient role) is also an instance of PCORnet medical procedure. Is that intended?

2. Do all the procedures represented in the procedure table realize a patient role? 
2A. Does a blood test performed after the patient goes home count as realizing a patient role? Perhaps it does. I just want to double check. 
2B. Also, do purely cosmetic procedures realize patient roles?

**Comment by CDowland** [comment]
Done.

**Comment by sjbost** [comment]
Answers to the above questions from Moonshot Aim 4 9/29 meeting discussion (forgot to click the Comment button that day...): 

1. Yes, this is intended given the current definition of health care encounter. 
2. Yes, theoretically, those examples would be included.
