### ISSUE TITLE
MIREOT 'date' from Apollo-SV

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#27]
Please.

http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000429

**Comment by CDowland** [comment]
I will take care of this as soon as we reach a decision on which class to use for LVs that are times, since a similar approach is needed for those. Examples include 'admit time' and 'discharge time' from the encounter table. I'm leaning toward APOLLO's 'name of a temporal interval,' but others might have better ideas. Once a decision is reached, I will MIREOT both.

**Comment by CDowland** [comment]
I went ahead and did this. I MIREOTed 'date' from APOLLO_SV, along with its parent class, 'name of temporal region,' as the latter connects 'identifier' to 'date' in the hierarchy. 

I also MIREOTed the other child classes of 'name of temporal region.' These are 'name of a temporal boundary' and 'name of temporal interval.' I suspect the latter will be what we use for the LV of time fields, just as we're using 'date' for the LV of date fields. 

These changes have been pushed to the devel branch.

I was going to wait because I wanted to do it all at once and we've not yet finalized how we're handling time fields, but the table you're currently working with has a date field, but not a time field, and I don't want to delay your progress.
